all: notebook.sh 

clean:
	rm -f notebook.sh

notebook.sh:
	wget -O notebook.sh https://raw.githubusercontent.com/avitase/phdscripts/master/hepana-notebook/hepana-notebook.sh
	chmod u+x-w notebook.sh
